msm8994: libhwcomposer: Move mdpHw declaration under DYNAMIC_FPS flagunder DYNAMIC_FPS flag
-Variable is used only when DYNAMIC_FPS is defined. Also resolves the following build errors:

-error: use of undeclared identifier 'mdpHw'
-error: unused variable 'mdpHw' [-Werror,-Wunused-variable]
Change-Id: I69423f4ea942a4adc346a2dad7de33ad552cf51c
Signed-off-by: Marc Babad <blitzkrieg.marc02@gmail.com>