msm8994: libhwcomposer: Silence build error/s
Variable is used only when DYNAMIC_FPS is defined. Also resolves the following errors:
 -hwc_utils.cpp:1078:21: error: use of undeclared identifier 'mdpHw'
 -hwc_utils.cpp:1086:29: error: use of undeclared identifier 'mdpHw'
 -hwc_utils.cpp:1087:41: error: use of undeclared identifier 'mdpHw'
 -error: unused variable 'mdpHw' [-Werror,-Wunused-variable]
 -hwc.cpp:519:5: error: unannotated fall-through between switch labels [-Wer
ror,-Wimplicit-fallthrough]

Change-Id: Ia89a6b5fe698a1f9a90fa8bb20c432920f3fef89