msm8994: libhwcomposer: Move mdpHw declaration under DYNAMIC_FPS flag
Variable is used only when DYNAMIC_FPS is defined
Also resolves the following build errors:
 -hwc_utils.cpp:1078:21: error: use of undeclared identifier 'mdpHw'
 -hwc_utils.cpp:1086:29: error: use of undeclared identifier 'mdpHw'
 -hwc_utils.cpp:1087:41: error: use of undeclared identifier 'mdpHw'

Change-Id: I4e1e84703b01b8903512e1f7411913bf255fa544
Signed-off-by: Marc Babad <blitzkrieg.marc02@gmail.com>